#!/usr/bin/bash

set -xe
time cargo test
time cargo test --no-default-features
time cargo test --all-targets
time cargo test --no-default-features --all-targets
time cargo test --no-default-features --features='alloc'
time cargo test --all-features
time cargo test --all-targets --all-features
echo "!!! All tests done successfully."
